apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kaf-cronjob-{{ topic }}
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kaf
            image: your-docker-image-for-kaf
            args: ["{{ topic }}"]
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
          restartPolicy: OnFailure
